baseURL = 'https://pennwest-california-programmingclub.github.io/'
languageCode = 'en-us'
title = 'PennWest Software Development Club'
theme = 'ananke'
publishDir = 'docs'
[params]
  homeFeed = "posts"
  custom_css = ["css/titleblast.css", "css/customfonts.css"]
  site_logo = "/img/Logo-Final.svg"


